"""
    render_summary_table(stats::SummaryStats; digits::Integer=3) -> String

Render a compact plain-text table for [`SummaryStats`](@ref).

# Arguments
- `stats`: descriptive statistics generated by [`summarize_numeric`](@ref).
- `digits`: decimal digits used for floating-point values.

# Returns
A multi-line string with one metric per row.

# Examples
```jldoctest
julia> using BiostatsInteractive

julia> stats = summarize_numeric([1, 2, 3]);

julia> println(render_summary_table(stats; digits=2))
count   3
mean    2.00
std     1.00
min     1.00
median  2.00
max     3.00
```
"""
function render_summary_table(stats::SummaryStats; digits::Integer=3)::String
    digits < 0 && throw(ArgumentError("digits must be non-negative"))

    io = IOBuffer()
    println(io, "count\t", stats.n)
    println(io, "mean\t", round(stats.mean; digits=digits))
    println(io, "std\t", round(stats.std; digits=digits))
    println(io, "min\t", round(stats.minimum; digits=digits))
    println(io, "median\t", round(stats.median; digits=digits))
    print(io, "max\t", round(stats.maximum; digits=digits))

    return String(take!(io))
end
