"""
    SummaryStats

Container for descriptive statistics generated by [`summarize_numeric`](@ref).

# Fields
- `n::Int`: number of non-missing values included.
- `mean::Float64`: arithmetic mean.
- `std::Float64`: sample standard deviation (`n - 1` denominator when `n > 1`, else `0.0`).
- `minimum::Float64`: smallest observed value.
- `median::Float64`: median value.
- `maximum::Float64`: largest observed value.
"""
Base.@kwdef struct SummaryStats
    n::Int
    mean::Float64
    std::Float64
    minimum::Float64
    median::Float64
    maximum::Float64
end

"""
    summarize_numeric(values::AbstractVector{<:Union{Missing, Real}}) -> SummaryStats

Compute descriptive summary statistics for a numeric vector while ignoring `missing` values.

# Arguments
- `values`: numeric input that may include `missing`.

# Returns
`SummaryStats` containing `n`, `mean`, `std`, `minimum`, `median`, and `maximum`.

# Errors
- Throws `ArgumentError` if no non-missing values are available.

# Examples
```jldoctest
julia> using BiostatsInteractive

julia> summarize_numeric([1.0, 2.0, missing, 4.0]).n
3
```
"""
function summarize_numeric(values::AbstractVector{<:Union{Missing, Real}})::SummaryStats
    clean = Float64[]
    sizehint!(clean, length(values))
    for v in values
        ismissing(v) && continue
        push!(clean, Float64(v))
    end

    isempty(clean) && throw(ArgumentError("values must contain at least one non-missing numeric observation"))

    n = length(clean)
    μ = sum(clean) / n

    σ = if n > 1
        centered_ss = sum((x - μ)^2 for x in clean)
        sqrt(centered_ss / (n - 1))
    else
        0.0
    end

    sorted = sort(clean)
    mid = fld(n + 1, 2)
    med = isodd(n) ? sorted[mid] : (sorted[mid] + sorted[mid + 1]) / 2

    return SummaryStats(
        n = n,
        mean = μ,
        std = σ,
        minimum = first(sorted),
        median = med,
        maximum = last(sorted),
    )
end
